BATCH_SIZE: 32
CLASSES: 4
LEARNING_RATE: 0.01
AUGMENTATION: True

VGG16:
  AUGMENTATION: True
  IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
  BATCH_SIZE: 32
  INCLUDE_TOP: False
  EPOCHS: 5
  CLASSES: 4
  WEIGHTS: imagenet
  LEARNING_RATE: 0.01

VGG19:
  AUGMENTATION: True
  IMAGE_SIZE: [224, 224, 3] # as per VGG 19 model
  BATCH_SIZE: 32
  INCLUDE_TOP: False
  EPOCHS: 50
  CLASSES: 4
  WEIGHTS: imagenet
  LEARNING_RATE: 0.01

RESNET:
  AUGMENTATION: True
  IMAGE_SIZE: [224, 224, 3] # as per Resnet model
  BATCH_SIZE: 32
  INCLUDE_TOP: False
  EPOCHS: 50
  CLASSES: 4
  WEIGHTS: imagenet
  LEARNING_RATE: 0.01

MOBILENET:
  AUGMENTATION: True
  IMAGE_SIZE: [224, 224, 3] # as per MOBILENET model
  BATCH_SIZE: 32
  INCLUDE_TOP: False
  EPOCHS: 50
  CLASSES: 4
  WEIGHTS: imagenet
  LEARNING_RATE: 0.01

MOBILENETV2:
  AUGMENTATION: True
  IMAGE_SIZE: [224, 224, 3] # as per MOBILENETV2 model
  BATCH_SIZE: 32
  INCLUDE_TOP: False
  EPOCHS: 50
  CLASSES: 4
  WEIGHTS: imagenet
  LEARNING_RATE: 0.01

INCEPTIONV3:
  AUGMENTATION: True
  IMAGE_SIZE: [299, 299, 3] # as per InceptionV3 model
  BATCH_SIZE: 32
  INCLUDE_TOP: False
  EPOCHS: 10
  CLASSES: 4
  WEIGHTS: imagenet
  LEARNING_RATE: 0.01

Xception:
  AUGMENTATION: True
  IMAGE_SIZE: [299, 299, 3] # as per Xception model
  BATCH_SIZE: 32
  INCLUDE_TOP: False
  EPOCHS: 10
  CLASSES: 4
  WEIGHTS: imagenet
  LEARNING_RATE: 0.01

